---
title: "EDA analysis"
output: html_document
---

```{r}
library(tidyverse)
# download the data
df_participation <- read_csv("https://catalogue.data.gov.bc.ca/dataset/6d9db663-8c30-43ec-922b-d541d22e634f/resource/646530d4-078c-4815-8452-c75639962bb4/download/provincial_voter_participation_by_age_group.csv")
df_result <- read_csv("https://catalogue.data.gov.bc.ca/dataset/44914a35-de9a-4830-ac48-870001ef8935/resource/fb40239e-b718-4a79-b18f-7a62139d9792/download/provincial_voting_results.csv")
```

```{r}
# calculate vote rate based on ED
df_vote_rate_by_ED <- df_participation %>% filter(EVENT_YEAR == '2017') %>%
  group_by(ED_ABBREVIATION) %>%
  summarise(vote_rate = sum(PARTICIPATION)/sum(REGISTERED_VOTERS))

# calculate election compatability based on ED
df1 <- df_result %>% 
  filter (EVENT_YEAR== 2017) %>%
  group_by(ED_ABBREVIATION) %>%
  summarise(TOTAL_VOTES_CONSIDERED = sum(VOTES_CONSIDERED))

df2 <- df_result %>% 
  filter (EVENT_YEAR== 2017, ELECTED== 'Y') %>%
  group_by(ED_ABBREVIATION) %>%
  summarise(WINNER_VOTES = sum(VOTES_CONSIDERED))

df_compete_by_ED <- left_join(df1, df2)

df_compete_by_ED <- df_compete_by_ED %>% 
  mutate (WINNER_AGAINST_RUNNERSUP_VOTES = round(WINNER_VOTES/(TOTAL_VOTES_CONSIDERED - WINNER_VOTES), 2)) %>% 
  select(ED_ABBREVIATION, WINNER_AGAINST_RUNNERSUP_VOTES)

# merge the two results and produce final dataframe
df_final <- left_join(df_vote_rate_by_ED, df_compete_by_ED)

df_final

```

```{r}
ggplot(df_final) +
    aes(x = WINNER_AGAINST_RUNNERSUP_VOTES,
        y = vote_rate) +
    geom_point() +
    geom_smooth(se = FALSE, size = 2, method = 'lm')

```



