% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{report}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={pvp},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=2cm]{geometry}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\renewcommand{\chaptername}{Part}
\newcommand{\fullline}{\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}}
\newcommand{\bminione}{\begin{minipage}{0.75 \textwidth}}
\newcommand{\bminitwo}{\begin{minipage}{0.25 \textwidth}}
\newcommand{\emini}{\end{minipage}}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{pvp}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Autogenerated data summary from dataMaid}
\author{}
\date{\vspace{-2.5em}2020-11-21 10:57:26}

\begin{document}
\maketitle

\hypertarget{data-report-overview}{%
\chapter{Data report overview}\label{data-report-overview}}

The dataset examined has the following dimensions:

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.33\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.33\columnwidth}\raggedright
Number of observations\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
2352\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.33\columnwidth}\raggedright
Number of variables\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
8\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{checks-performed}{%
\subsection{Checks performed}\label{checks-performed}}

The following variable checks were performed, depending on the data type
of each variable:

\begin{longtable}[]{@{}lcccccccc@{}}
\toprule
\begin{minipage}[b]{0.28\columnwidth}\raggedright
~\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering
character\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering
factor\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering
labelled\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\centering
haven labelled\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering
numeric\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering
integer\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
logical\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering
Date\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.28\columnwidth}\raggedright
Identify miscoded missing values\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright
Identify prefixed and suffixed whitespace\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright
Identify levels with \textless{} 6 obs.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright
Identify case issues\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright
Identify misclassified numeric or integer variables\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright
Identify outliers\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
\(\times\)\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

Please note that all numerical values in the following have been rounded
to 2 decimals.

\hypertarget{summary-table}{%
\chapter{Summary table}\label{summary-table}}

\begin{longtable}[]{@{}llrrc@{}}
\toprule
\begin{minipage}[b]{0.20\columnwidth}\raggedright
~\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\raggedright
Variable class\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
\# unique values\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Missing observations\strut
\end{minipage} & \begin{minipage}[b]{0.14\columnwidth}\centering
Any problems?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\protect\hyperlink{event_name}{event\_name}\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
4\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\protect\hyperlink{event_year}{event\_year}\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
4\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\protect\hyperlink{ed_abbreviation}{ed\_abbreviation}\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
132\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\protect\hyperlink{ed_name}{ed\_name}\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
124\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\protect\hyperlink{age_group}{age\_group}\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
7\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\protect\hyperlink{participation}{participation}\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
1905\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\protect\hyperlink{registered_voters}{registered\_voters}\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
2033\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\protect\hyperlink{event_date_text}{event\_date\_text}\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
4\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{variable-list}{%
\chapter{Variable list}\label{variable-list}}

\hypertarget{event_name}{%
\section{event\_name}\label{event_name}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.34\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
4\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
``General Election 2017''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{profile_pvp_files/figure-latex/Var-1-event-name-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{event_year}{%
\section{event\_year}\label{event_year}}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
4\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
``2017''\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Reference category\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
2005\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{profile_pvp_files/figure-latex/Var-2-event-year-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{ed_abbreviation}{%
\section{ed\_abbreviation}\label{ed_abbreviation}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
132\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
``ABM''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{profile_pvp_files/figure-latex/Var-3-ed-abbreviation-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  The following suspected missing value codes enter as regular values:
  "NAN".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{ed_name}{%
\section{ed\_name}\label{ed_name}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.24\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
124\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
``Burnaby North''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{profile_pvp_files/figure-latex/Var-4-ed-name-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{age_group}{%
\section{age\_group}\label{age_group}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
``18-24''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{profile_pvp_files/figure-latex/Var-5-age-group-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{participation}{%
\section{participation}\label{participation}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.24\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
1905\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
2866\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
1875.75; 4135.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
417; 9498\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{profile_pvp_files/figure-latex/Var-6-participation-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "9498".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{registered_voters}{%
\section{registered\_voters}\label{registered_voters}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.21\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
2033\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
5139\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
3415; 6895.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
768; 15027\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{profile_pvp_files/figure-latex/Var-7-registered-voters-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "12555", "12581", "12688", "13176", "13627", "15027".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{event_date_text}{%
\section{event\_date\_text}\label{event_date_text}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
4\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
``05/09/2017''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{profile_pvp_files/figure-latex/Var-8-event-date-text-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

Report generation information:

\begin{itemize}
\item
  Created by: Rafael Pilliard-Hellwig (username: \texttt{raf}).
\item
  Report creation time: Sat Nov 21 2020 10:57:26
\item
  Report was run from directory:
  \texttt{/Users/raf/Dropbox/mds/b3/522\_dwf/bc\_election\_turnout}
\item
  dataMaid v1.4.0 {[}Pkg: 2019-12-10 from CRAN (R 4.0.0){]}
\item
  R version 4.0.3 (2020-10-10).
\item
  Platform: x86\_64-apple-darwin17.0 (64-bit)(macOS Catalina 10.15.7).
\item
  Function call:
  \texttt{dataMaid::makeDataReport(data\ =\ pvp,\ file\ =\ here::here("eda",\ \ \ \ \ \ "profile\_pvp.Rmd"),\ replace\ =\ TRUE)}
\end{itemize}

\end{document}
