# author: team 19
# data: 2020-12-01

"This script is the first plot script of milestone 2 of
522 group19 project. This script takes in the processed
data generated by script#2 and generates a scatter plot
for interpretation. This script takes two arguments:
1) a path/filename pointing to the data.
2) a path/filename prefix where to write the figure to and what to call it
(e.g., results/this_eda.png)

Usage: src/make_figures_scatter.R [--input=<input>] [--out_dir=<out_dir>]

Options:
--input=<input>      The file path to the cleaned data file.
                     [default: data/processed/bc_election_by_district.rds]
--out_dir=<out_dir>  The file path to where the processed data should be saved.
                     [default: doc/images]
" -> doc

library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
library(docopt)
library(stringr)

opt <- docopt(doc)

dir.create(here::here(opt$out_dir), recursive = TRUE, showWarnings = FALSE)

dr_scatter_plot <- function(input, out_dir) {
  data <- readRDS(input)
  scatter_plot <- data %>%
    tidyr::drop_na(competitiveness) %>%
    mutate(across(event_name, forcats::fct_lump,
      n = 4,
      other_level = "Other By-Elections"
    )) %>%
    ggplot(aes(x = competitiveness, y = turnout)) +
    geom_point(aes(shape = event_name), na.rm = TRUE) +
    geom_smooth(method = "lm", formula = y ~ x,
                colour = "black", na.rm = TRUE) +
    scale_y_continuous(labels = scales::percent_format(1)) +
    scale_x_continuous(labels = scales::percent_format(1)) +
    labs(
      title = "The more competitive the race, the greater the turnout",
      caption = "Source: Authors' own analysis of Elections BC open data",
      y = "Voter Turnout Within Electoral District",
      x = glue::glue(
        "Competitiveness
        (Vote Share of the Runner-Up MINUS Vote Share of the Winner)"),
      shape = "Election"
    ) +
    ggthemes::theme_fivethirtyeight() +
    theme(
      axis.title = element_text(),
      legend.position = "right",
      legend.direction = "vertical")
  ggsave(
    filename = here::here(out_dir, "scatter_plot.png"),
    width = 8, height = 6
  )
}

dr_scatter_plot(opt[["--input"]], opt[["--out_dir"]])
