# author: team 19
# data: 2020-12-01

"This script is the second plot script of milestone 2 of
522 group19 project. This script takes in the processed data
generated by script#2 and generates a cow plot. for
interpretation. This script takes two arguments:
1) a path/filename pointing to the data.
2) a path/filename prefix where to write the figure to and what to call it
(e.g., results/this_eda.png)

Usage: src/make_figures_cow.R [--input=<input>] [--out_dir=<out_dir>]

Options:
--input=<input>      The file path to the cleaned data file.
                     [default: data/processed/bc_election_by_district.rds]
--out_dir=<out_dir>  The file path to where the processed data should be saved.
                     [default: doc/images]
" -> doc

library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
library(docopt)
library(stringr)

opt <- docopt(doc)

dir.create(here::here(opt$out_dir), recursive = TRUE, showWarnings = FALSE)

dr_cow_plot <- function(input, out_dir) {
  data <- readRDS(input)
  thm <- ggthemes::theme_fivethirtyeight() + theme(axis.title = element_text())
  plot1 <- ggpubr::ggqqplot(na.omit(data$competitiveness),
    ylab = "competitiveness", ggtheme = thm
  )
  plot2 <- ggpubr::ggqqplot(na.omit(data$turnout), ylab = "turnout",
                            ggtheme = thm)
  cow_plot <- cowplot::plot_grid(plot1, plot2, ncol = 2)
  ggsave(
    filename = here::here(out_dir, "cow_plot.png"), plot = cow_plot,
    width = 8, heigh = 4
  )
}

dr_cow_plot(opt[["--input"]], opt[["--out_dir"]])
