# author: Yuan Xiong
# data: 2020-11-25

"This script is the #3 script of milestone 2 of 522 group19 project. This
script takes in the processed data generated by script#2 and generates plots
for interpretation. This script takes two arguments:
1) a path/filename pointing to the data.
2) a path/filename prefix where to write the figure to and what to call it
(e.g., results/this_eda.png)

Usage: src/make_figures.R [--input=<input>] [--out_dir=<out_dir>]

Options:
--input=<input>      The file path to the cleaned data file.
                     [default: data/processed/bc_election_by_district.rds]
--out_dir=<out_dir>  The file path to where the processed data should be saved.
                     [default: doc/images]
" -> doc

library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
suppressMessages(library(GGally, warn.conflicts = FALSE))
library(docopt)
library(stringr)

opt <- docopt(doc)

dir.create(here::here(opt$out_dir), recursive = TRUE, showWarnings = FALSE)

dr_violin_plot <- function(input, out_dir) {
  data <- readRDS(input)
  violin_plot <- data %>%
    filter(str_detect(event_name, "General Election")) %>%
    ggplot(aes(y = turnout, x = factor(str_wrap(event_name, 15)))) +
    geom_violin(size = 1, na.rm = TRUE) +
    scale_y_continuous(labels = scales::percent_format(1)) +
    labs(
      title = "Electoral District (ED) Voter Turnout Rates",
      y = "Density of % of Eligible\nVoters Who Partcipated in ED",
      x = NULL
    ) +
    geom_point(stat = "summary", na.rm = TRUE, fun = mean)
  ggsave(filename = here::here(out_dir, "violin_plot.png"),
         width = 7, height = 7)
}

dr_violin_plot(opt[["--input"]], opt[["--out_dir"]])

dr_correlation_matrix <- function(input, out_dir) {
  data <- readRDS(input)
  cor_matrix <- data %>%
    select(where(is.numeric)) %>%
    GGally::ggcorr(label = TRUE, label_round = 2) +
    labs(title = "Correlation Matrix")
  ggsave(filename = here::here(out_dir, "cor_matrix.png"),
         width = 7, height = 7)
}

dr_correlation_matrix(opt[["--input"]], opt[["--out_dir"]])

dr_scatter_plot <- function(input, out_dir) {
  data <- readRDS(input)
  scatter_plot <- data %>%
    tidyr::drop_na(competitiveness) %>%
    mutate(across(event_name, forcats::fct_lump,
      n = 4,
      other_level = "Other By-Elections"
    )) %>%
    ggplot(aes(x = competitiveness, y = turnout)) +
    geom_point(aes(shape = event_name), na.rm = TRUE) +
    geom_smooth(method = "lm", formula = y ~ x,
                colour = "black", na.rm = TRUE) +
    scale_y_continuous(labels = scales::percent_format(1)) +
    scale_x_continuous(labels = scales::percent_format(1)) +
    labs(
      title = "The more competitive the race, the greater the turnout",
      caption = "Source: Elections BC Open Data",
      y = "Voter Turnout Within Electoral District",
      x = glue::glue(
        "Competitiveness
        (Vote Share of the Runner-Up MINUS Vote Share of the Winner)"),
      shape = "Election"
    ) +
    theme(legend.position = "right", legend.direction = "vertical")
  ggsave(
    filename = here::here(out_dir, "scatter_plot.png"),
    width = 8, height = 6
  )
}

dr_scatter_plot(opt[["--input"]], opt[["--out_dir"]])

dr_cow_plot <- function(input, out_dir) {
  data <- readRDS(input)
  plot1 <- ggpubr::ggqqplot(na.omit(data$competitiveness),
                            ylab = "competitiveness")
  plot2 <- ggpubr::ggqqplot(na.omit(data$turnout), ylab = "turnout")
  cow_plot <- cowplot::plot_grid(plot1, plot2, ncol = 2)
  ggsave(filename = here::here(out_dir, "cow_plot.png"), plot = cow_plot,
         width = 8, heigh = 4)
}

dr_cow_plot(opt[["--input"]], opt[["--out_dir"]])
