# author: Yuan Xiong
# data: 2020-11-25

"This script is the #3 script of milestone 2 of 522 group19 project. This script takes in the processed data
generated by script#2 and generates plots for interpretation. This script takes two arguments:
1) a path/filename pointing to the data.
2) a path/filename prefix where to write the figure to and what to call it (e.g., results/this_eda.png)
Usage: src/processed_data_to_plots.R --input=<input> --out_dir=<out_dir>

Options:
--input=<input>                   The file path to the cleaned data file.
--out_dir=<out_dir>               The file path to where the processed data should be saved.
" -> doc

library(tidyverse)
library(docopt)

opt <- docopt(doc)

dr_violin_plot <- function (input, out_dir) {
  data <- readRDS(input)
  violin_plot <- data %>%
    ggplot(aes(y = turnout, x = factor(str_wrap(event_name, 15)))) +
    geom_violin(size = 1) +
    scale_y_continuous(labels = scales::percent_format(1)) +
    labs(title = "Electoral District (ED) Voter Turnout Rates",
         y = "Density of % of Eligible\nVoters Who Partcipated in ED",
         x = NULL) +
    stat_summary(fun = mean)
  ggsave(filename = here::here(out_dir, 'violin_plot.png'))
}

dr_violin_plot(opt[['--input']], opt[['--out_dir']])

dr_correlation_matrix <- function (input, out_dir) {
   data <- readRDS(input)
   cor_matrix <- data %>%
     select(where(is.numeric)) %>%
     GGally::ggcorr(label = TRUE, label_round = 2) +
     labs(title = "Correlation Matrix")
   ggsave(filename = here::here(out_dir, 'cor_matrix.png'))
}

dr_correlation_matrix(opt[['--input']], opt[['--out_dir']])

dr_scatter_plot <- function(input, out_dir) {
   data <- readRDS(input)
   scatter_plot <- data %>%
     drop_na(competitiveness) %>%
     mutate(across(event_name, fct_lump, n = 4,
                   other_level = "Other By-Elections")) %>%
     ggplot(aes(x = competitiveness, y = turnout)) +
     geom_point(aes(shape = event_name)) +
     geom_smooth(method = "lm", formula = y ~ x, colour = "black") +
     scale_y_continuous(labels = scales::percent_format(1)) +
     scale_x_continuous(labels = scales::percent_format(1)) +
     labs(title = "The more competitive the race, the greater the turnout",
          caption = "Source: Elections BC Open Data",
          y = "Voter Turnout Within Electoral District",
          x = "Competitiveness\n(Vote Share of the Runner-Up MINUS Vote Share of the Winner)",
          shape = "Election") +
     theme(legend.position = "right", legend.direction = "vertical")
   ggsave(filename = here::here(out_dir, 'scatter_plot.png'))
}

dr_scatter_plot(opt[['--input']], opt[['--out_dir']])
