# author: Yuan Xiong
# data: 2020-11-25

"This script is the #3 script of milestone 2 of 522 group19 project. This script takes in the processed data
generated by script#2 and generates plots for interpretation. This script takes two arguments:
1) a path/filename pointing to the data.
2) a path/filename prefix where to write the figure to and what to call it (e.g., results/this_eda.png)

Usage: Rscript processed_data_to_plots.R <file_path_input> <file_path_output>
" -> doc

library(tidyverse)
library(docopt)

opt <- docopt(doc)

dr_violin_plot <- function (file_path_input, file_path_output) {
  data <- read_csv(file_path_input)
  violin_plot <- data %>% 
    ggplot(aes(y = turnout, x = factor(event_name))) +
    geom_violin(size = 1) +
    scale_y_continuous(labels = scales::percent) +
    labs(title = "Electoral District (ED) Voter Turnout Rates",
         x = "Percentage of Eligible Voters Who Partcipated in ED",
         y = "Density") +
    stat_summary(fun = mean)
  ggsave(path = 'file_path_output', filename = 'violin_plot.png')
}

dr_violin_plot(opt$file_path_input, opt$file_path_output)

dr_correlation_matrix <- function (file_path_input, file_path_output) {
  data <- read_csv(file_path_input)  
  cor_matrix <- data %>%
    select(where(is.numeric)) %>%
    GGally::ggcorr(label = TRUE, label_round = 2) +
    labs(title = "Correlation Matrix")
  ggsave(path = 'file_path_output', filename = 'cor_matrix.png')
}

dr_correlation_matrix(opt$file_path_input, opt$file_path_output)

dr_scatter_plot <- function(file_path_input, file_path_output) {
  data <- read_csv(file_path_input)
  scatter_plot <- data %>%
    drop_na(competitiveness) %>%
    mutate(across(event_name, fct_lump, n = 4, 
                  other_level = "Other By-Elections")) %>%
    ggplot(aes(x = competitiveness, y = turnout)) +
    geom_point(aes(shape = event_name)) +
    geom_smooth(method = "lm", formula = y ~ x, colour = "black") +
    scale_y_continuous(labels = scales::percent_format(1)) +
    scale_x_continuous(labels = scales::percent_format(1)) +
    labs(title = "The more competitive the race, the greater the turnout",
         caption = "Source: Elections BC Open Data",
         y = "Voter Turnout Within Electoral District",
         x = "Competitiveness\n(Vote Share of the Runner-Up MINUS Vote Share of the Winner)",
         shape = "Election") +
    theme(legend.position = "right", legend.direction = "vertical")
  ggsave(path = 'file_path_output', filename = 'scatter_plot.png')
}

dr_scatter_plot(opt$file_path_input, opt$file_path_output)
